---
abstract: 'Assemble a microsite with Handlebars'
author:
  - 'Shawn M Moore <code@sartak.org>'
  - 'Michael Reddick <michael.reddick@iinteractive.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Microsite-Assemble
requires:
  File::Next: 0
  JSON: 0
  Path::Class: 0
  Text::Handlebars: 0
  Text::Xslate: 0
  Try::Tiny: 0
resources:
  homepage: https://github.com/sartak/App-Microsite-Assemble
  repository: https://github.com/sartak/App-Microsite-Assemble.git
version: 0.02
